Repository bekindtomammals0/ASI_HR-Hiring-System_Group4, pull requests merged in 2023-08, with the labels that each got.

#52 Passed data from JobOpeningViewModel to ApplicationForm
  Basecode.WebApp/Controllers/JobOpeningController.cs
  Basecode.WebApp/Views/ApplicationForm/Index.cshtml
Labels: fix-attempt

#54 Backend/application form submit
  Basecode.WebApp/Controllers/ApplicationFormController.cs
  Basecode.WebApp/Controllers/JobOpeningController.cs
  Basecode.WebApp/Views/ApplicationForm/Index.cshtml
Labels: enhancement, help wanted

#51 Page Styles
  Basecode.WebApp/Views/Home/Index.cshtml
  Basecode.WebApp/Views/JobOpening/Index.cshtml
  Basecode.WebApp/Views/JobOpening/_JobAdd.cshtml
  Basecode.WebApp/Views/Shared/_CustomNavbar.cshtml
  Basecode.WebApp/wwwroot/css/home.css
  Basecode.WebApp/wwwroot/css/jobOpening.css
Labels: enhancement
