Repository bekindtomammals0/ASI_HR-Hiring-System_Group4, pull requests merged in 2023-07, with the labels that each got.

#29 Proj/workflows enhancement
  .github/workflows/dotnet.yml
Labels: documentation, enhancement

#30 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: enhancement

#33 Modify Navbar Routing
  Basecode.WebApp/Controllers/AccountManagerController.cs
  Basecode.WebApp/Views/Shared/_CustomNavbar.cshtml
Labels: fix-attempt

#36 Removed <select> tag from ApplicationForm/Index
  Basecode.WebApp/Views/ApplicationForm/Index.cshtml
Labels: fix-attempt

#38 Frontend/extract inline styles
  Basecode.WebApp/Views/AccountManager/Register.cshtml
  Basecode.WebApp/Views/Home/Index.cshtml
  Basecode.WebApp/Views/JobOpening/Index.cshtml
  Basecode.WebApp/Views/Login/Index.cshtml
  Basecode.WebApp/Views/Shared/_CustomNavbar.cshtml
  Basecode.WebApp/wwwroot/css/customNavbar.css
  Basecode.WebApp/wwwroot/css/home.css
  Basecode.WebApp/wwwroot/css/jobOpening.css
Labels: enhancement

#39 Dev fix null items
  .gitignore
  Basecode.Data/Migrations/20230713142313_Basecode.Data.Designer.cs
  Basecode.Data/Migrations/20230713142313_Basecode.Data.cs
  Basecode.Data/Migrations/BasecodeContextModelSnapshot.cs
  Basecode.Data/ViewModels/JobOpeningViewModel.cs
  Basecode.Data/obj/Basecode.Data.csproj.nuget.dgspec.json
  Basecode.Data/obj/Debug/net7.0/Basecode.Data.AssemblyInfo.cs
  Basecode.Data/obj/project.assets.json
  Basecode.Services/obj/Basecode.Services.csproj.nuget.dgspec.json
  Basecode.Services/obj/Debug/net7.0/Basecode.Services.AssemblyInfo.cs
  Basecode.Services/obj/Debug/net7.0/ref/Basecode.Services.dll
  Basecode.Services/obj/Debug/net7.0/refint/Basecode.Services.dll
  Basecode.Services/obj/project.assets.json
  Basecode.WebApp/Controllers/AccountManagerController.cs
  Basecode.WebApp/Controllers/JobOpeningController.cs
  Basecode.WebApp/Views/JobOpening/Index.cshtml
  Basecode.WebApp/Views/JobOpening/_JobAdd.cshtml
  Basecode.WebApp/Views/Shared/_CustomNavbar.cshtml
Labels: fix-attempt

#37 Prepare `CharacterReference` backend files in Data layer
  Basecode.Data/BasecodeContext.cs
  Basecode.Data/Interfaces/ICharacterReferenceRepository.cs
  Basecode.Data/Models/CharacterReference.cs
  Basecode.Data/Repositories/CharacterReferenceRepository.cs
Labels: enhancement

#41 backend/prepare-data-viewmodels-and-service-files
  Basecode.Services/Interfaces/ILookupService.cs
  Basecode.Services/Services/LookupService.cs
Labels: fix-attempt

#44 Update Index.cshtml
  Basecode.WebApp/Views/ApplicationForm/Index.cshtml
Labels: enhancement

#45 Backend/prepare application form
  Basecode.Data/ViewModels/ApplicationFormViewModel.cs
  Basecode.Services/Interfaces/IApplicantService.cs
  Basecode.Services/Interfaces/ICVService.cs
  Basecode.Services/Interfaces/ICharacterReferenceService.cs
  Basecode.Services/Services/ApplicantService.cs
  Basecode.Services/Services/CVService.cs
  Basecode.Services/Services/CharacterReferenceService.cs
Labels: enhancement
